# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """─── AI Task Generator Service ─────────────────────────────────────────────────
    Polyglot gRPC: NestJS (client) ↔ Python (server)
    Features: Task Breakdown (Gemini) + Time Estimation (RAG via pgvector)
    ────────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTasks = channel.unary_unary(
                '/ai.AIService/GenerateTasks',
                request_serializer=ai__service__pb2.GenerateTasksRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GenerateTasksResponse.FromString,
                _registered_method=True)
        self.EstimateTime = channel.unary_unary(
                '/ai.AIService/EstimateTime',
                request_serializer=ai__service__pb2.EstimateTimeRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EstimateTimeResponse.FromString,
                _registered_method=True)
        self.StoreTaskEmbedding = channel.unary_unary(
                '/ai.AIService/StoreTaskEmbedding',
                request_serializer=ai__service__pb2.StoreTaskEmbeddingRequest.SerializeToString,
                response_deserializer=ai__service__pb2.StoreTaskEmbeddingResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """─── AI Task Generator Service ─────────────────────────────────────────────────
    Polyglot gRPC: NestJS (client) ↔ Python (server)
    Features: Task Breakdown (Gemini) + Time Estimation (RAG via pgvector)
    ────────────────────────────────────────────────────────────────────────────────

    """

    def GenerateTasks(self, request, context):
        """Generate tasks from a goal/project description using Gemini LLM
        and estimate pomodoros for each via RAG on user's past tasks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateTime(self, request, context):
        """Estimate pomodoros for a single task using RAG (pgvector cosine similarity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTaskEmbedding(self, request, context):
        """Store a task embedding after task creation/completion (for RAG index).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTasks,
                    request_deserializer=ai__service__pb2.GenerateTasksRequest.FromString,
                    response_serializer=ai__service__pb2.GenerateTasksResponse.SerializeToString,
            ),
            'EstimateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateTime,
                    request_deserializer=ai__service__pb2.EstimateTimeRequest.FromString,
                    response_serializer=ai__service__pb2.EstimateTimeResponse.SerializeToString,
            ),
            'StoreTaskEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTaskEmbedding,
                    request_deserializer=ai__service__pb2.StoreTaskEmbeddingRequest.FromString,
                    response_serializer=ai__service__pb2.StoreTaskEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """─── AI Task Generator Service ─────────────────────────────────────────────────
    Polyglot gRPC: NestJS (client) ↔ Python (server)
    Features: Task Breakdown (Gemini) + Time Estimation (RAG via pgvector)
    ────────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GenerateTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GenerateTasks',
            ai__service__pb2.GenerateTasksRequest.SerializeToString,
            ai__service__pb2.GenerateTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/EstimateTime',
            ai__service__pb2.EstimateTimeRequest.SerializeToString,
            ai__service__pb2.EstimateTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTaskEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/StoreTaskEmbedding',
            ai__service__pb2.StoreTaskEmbeddingRequest.SerializeToString,
            ai__service__pb2.StoreTaskEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
